image:
  repository: csi-shared-lvm
  tag: latest
  pullPolicy: IfNotPresent

sidecars:
  provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
  attacher:
    image: registry.k8s.io/sig-storage/csi-attacher:v4.9.0
  resizer:
    image: registry.k8s.io/sig-storage/csi-resizer:v1.14.0
  registrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.14.0
  livenessprobe:
    image: registry.k8s.io/sig-storage/livenessprobe:v2.16.0

driver:
  allowedVolumeGroups: "" # comma-separated

rbac:
  create: true

serviceAccount:
  create: true
  name: csi-shared-lvm
